// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyLpmmxwzRDN60wV304bQFWf9Nw_t0TI',
    appId: '1:151075562725:web:f2459d648637e9dc3ea00c',
    messagingSenderId: '151075562725',
    projectId: 'freecodecamp-course-app',
    authDomain: 'freecodecamp-course-app.firebaseapp.com',
    storageBucket: 'freecodecamp-course-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9JuOs_MvM-ZocA9iLibmKluU2GNGFhM',
    appId: '1:151075562725:android:eda8ecab62771e813ea00c',
    messagingSenderId: '151075562725',
    projectId: 'freecodecamp-course-app',
    storageBucket: 'freecodecamp-course-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrAb3GF1w2rH_1DwJC32Vn0roP0J0DsGU',
    appId: '1:151075562725:ios:88e4d487519349b03ea00c',
    messagingSenderId: '151075562725',
    projectId: 'freecodecamp-course-app',
    storageBucket: 'freecodecamp-course-app.appspot.com',
    iosBundleId: 'com.denistomas.freeCodeCampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrAb3GF1w2rH_1DwJC32Vn0roP0J0DsGU',
    appId: '1:151075562725:ios:617440c4703aa4cf3ea00c',
    messagingSenderId: '151075562725',
    projectId: 'freecodecamp-course-app',
    storageBucket: 'freecodecamp-course-app.appspot.com',
    iosBundleId: 'com.denistomas.freeCodeCampApp.RunnerTests',
  );
}
